### ISSUE TITLE
Loose game immediate if there are 0 moves left and the game is not won

### ISSUE THREAD

**Issue by darkdragon-001** [tfuxu/floodit#18] opened 2024-10-06 15:02 UTC
### Is there an existing issue for this?

- [X] I have checked the existing issues

### Describe your issue

When there are 0 moves left and there are still more than one color on the board (not won) there is no possibility of winning any more. Loose the game immediately instead of waiting for the user to do another move.

**Comment by tfuxu** [comment] 2024-10-06 15:06
This was fixed in 1.1.0, I've pushed an update to Flathub, but it might take a couple of hours before it will be available to download.

Duplicate of #8.

**Closed by tfuxu** 2024-10-06 15:06 UTC
Labels: bug
